inc_cparam = /home/dww01/ABECrypto/cryptoparam/
inc_matrix = /home/dww01/ABECrypto/lsssmatrix/
inc_accp = /home/dww01/ABECrypto/accesspolicy/
inc_murmur = /home/dww01/ABECrypto/murmurhash/
inc_param = /home/dww01/ABECrypto/param/

obj_