Obj_Dir = /home/dww01/ABECrypto/obj/
par = param/

all: abeparam.o curve_param.o

abeparam.o: abeparam.cpp
	g++ abeparam.cpp -c -o $(Obj_Dir)$(par)abeparam.o

curve_param.o: curve_param.cpp
	g++ curve_param.cpp -c -o $(Obj_Dir)$(par)curve_param.o